name: quantum
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyscf
  - pip
  - pip:
      - qiskit
      - qiskit-aer
      - qiskit-algorithms
      - qiskit-nature
      - qiskit-ibm-runtime
      - pylatexenc
      - jupyter
      - python-dotenv