name: quantum
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyscf
  - qiskit
  - qiskit-algorithms
  - qiskit-nature
  - pip
  - pip:
      - -e .[dev]