[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vqe-quantum-simulation"
version = "0.1.0"
description = "VQE and FCI simulation utilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "pylatexenc",
    "pyscf",
    "python-dotenv",
    "qiskit",
    "qiskit-aer",
    "qiskit-algorithms",
    "qiskit-ibm-runtime",
    "qiskit-nature",
    "scikit-learn",
    "scipy"
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "jupyter",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["src", "src.*"]
